"""Response models for the document endpoints.

Declaring the response shape as a Pydantic model means the frontend has one
documented contract to rely on, and FastAPI validates every response against
it before sending — a typo in the service layer becomes a loud server error
instead of a silently malformed payload.
"""

from pydantic import BaseModel, Field


class DocumentMetadata(BaseModel):
    """What the API returns after a document is successfully stored."""

    document_id: str = Field(
        description="Unique ID generated by the server. Also the stored filename.",
        examples=["3f1c9f0e-7b2a-4a1e-9f5b-2c8d0e4a6b31"],
    )
    filename: str = Field(
        description="Original filename as it was on the user's machine.",
        examples=["research-paper.pdf"],
    )
    file_type: str = Field(
        description="Document format. Only 'pdf' is supported in this milestone.",
        examples=["pdf"],
    )
    file_size: int = Field(
        description="Size of the stored file in bytes.",
        examples=[102400],
    )
    uploaded_at: str = Field(
        description="UTC time the upload completed, in ISO 8601.",
        examples=["2026-01-01T12:00:00+00:00"],
    )
